todoproject/todoapp/urls.py
from django.urls import path
from . import views

app_name = 'todoapp'
urlpatterns = [

    path('', views.add, name='add'),
    # path('details',views.detail ,name='details'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('update/<int:id>/', views.update, name='update'),
    path('list-home/', views.TasklistView.as_view(), name='list-home'),
    path('detail-home/<int:pk>/', views.TaskDetailView.as_view(), name='detail-home'),

]

todoproject/todoproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

todoproject/todoapp/models.py
from django.db import models
# Create your models here.
class Task(models.Model):
    name=models.CharField(max_length=250)
    priority=models.IntegerField()
    date=models.DateField()
    def __str__(self):
        return self.name

todoproject/todoapp/forms.py
from django import forms
from .models import Task


class TodoForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'priority', 'date']

todoproject/todoapp/views.py
from django.shortcuts import render, redirect
from .models import Task
from .forms import TodoForm
from django.views.generic import ListView
from django.views.generic.detail import DetailView


# Create your views here.
def add(request):
    task1 = Task.objects.all()
    if request.method == 'POST':
        name = request.POST.get('name', '')
        priority = request.POST.get('priority', '')
        date = request.POST.get('date', '')
        task = Task(name=name, priority=priority, date=date)
        task.save()
    return render(request, "home.html", {'tsk': task1})


# return render(request, 'details.html',)
# def detail(request):
def delete(request, id):
    if request.method == 'POST':
        task = Task.objects.get(id=id)
        task.delete()
        return redirect('/')
    return render(request, 'delete.html')


def update(request, id):
    task = Task.objects.get(id=id)
    f = TodoForm(request.POST or None, instance=task)

    if f.is_valid():
        f.save()
        return redirect('/')
    return render(request, 'edit.html', {'f': f, 'task': task})


class TasklistView(ListView):
    model = Task
    template_name = 'home.html'
    context_object_name = 'tsk'


class TaskDetailView(DetailView):
    model = Task
    template_name = 'details.html'
    context_object_name = 'tsk'

todoproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
<!--    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
    <link rel="stylesheet" href="{% static 'style.css' %}">
<body>
{% block content %}
{% endblock %}
</body>
</html>

todoproject/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <p> Are You Sure this Task is Done?</p>
    <button type="submit"> confirm </button>
</form>
{% endblock %}

todoproject/templates/details.html
{% extends 'base.html' %}
{% block content %}

 <div class="shadow card">
     <div class="card-body">
         <h5 class="card title">
             {{tsk.name}}
         </h5>
         <p><b>{{tsk.priority}}</b></p>
         <p><b>{{tsk.date}}</b></p>
         <a class="btn btn-danger" href="{% url 'todoapp:delete' tsk.id %}">done</a>
         <a class="btn btn-success" href="{% url 'todoapp:update' tsk.id %}">update</a>
     </div>
 </div>

{% endblock %}

todoproject/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<form method="POST" >
  {% csrf_token %}
  {{ f.as_p }}
  <button type="submit"> confirm </button>
</form>
{% endblock %}

todoproject/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid" >
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1> Todo </h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="POST" class="p-3 shadow">
                {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" name="name" placeholder="Task"><br>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="priority" placeholder="Enter your priority"><br>
                    </div>
                    <div class="form-group">
                        <input type="date" class="form-control" name="date" placeholder="Date"><br>
                    </div>
                        <input type="submit" class="btn btn-success">
            </form>
        </div>

        <div class="col-md-6">
            <h4>Task to be completed</h4>
            {% for i in tsk %}
            <div class="shadow card">
                <div class="card-body">
                    <h5 class="card title">
                        {{i.name}}
                    </h5>
                    <p><b>{{i.priority}}</b></p>
                    <p><b>{{i.date}}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">done</a>
                    <a class="btn btn-success" href="{% url 'todoapp:update' i.id %}">update</a>
                </div>
            </div>
            <br>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}}